image: Visual Studio 2015
platform: x64
configuration: Release
environment:
  matrix:
  - GENERATOR: "Visual Studio 14 2015"
  - GENERATOR: "Visual Studio 14 2015 Win64"

before_build:
  - cmake -G "%GENERATOR%"

build:
  project: PACKAGE.vcxproj

artifacts:
  - path: '*.msi'
    name: Installer
  - path: Release\audioswitch.exe
    name: Executable

deploy:
  provider: Environment
  name: AudioSwitchGithub
  on:
    appveyor_repo_tag: true
